#!/bin/bash
#----------------------------------------------------------------------------------------------------
# ante - Copyright header management - Shared functions
# Auto-generated by ante. Do not edit manually.
#----------------------------------------------------------------------------------------------------

# Configuration values from deno.json
WIDTH=100
SEPARATOR_CHAR="-"
COMMENT_PREFIX="//"
NAME_COL=40
EMAIL_COL=65
LICENSE_URL_COL=40
MAINTAINER_COL=75
SPDX_LICENSE="MPL-2.0"
LICENSE_URL="https://mozilla.org/MPL/2.0"
MAINTAINER_EMAIL="ort@hiisi.digital"

# Generate separator line
generate_separator() {
    local len=$((WIDTH - ${#COMMENT_PREFIX}))
    printf "%s" "$COMMENT_PREFIX"
    printf '%*s' "$len" '' | tr ' ' "$SEPARATOR_CHAR"
    echo
}

# Format a copyright line with column alignment
format_copyright_line() {
    local year_part="$1"
    local name="$2"
    local email="$3"
    
    local prefix
    if [ -n "$year_part" ]; then
        prefix="$COMMENT_PREFIX Copyright (c) $year_part"
    else
        prefix="$COMMENT_PREFIX"
    fi
    
    local prefix_len=${#prefix}
    local padding_to_name=$((NAME_COL - prefix_len))
    [ "$padding_to_name" -lt 1 ] && padding_to_name=1
    
    local name_end=$((NAME_COL + ${#name}))
    local padding_to_email=$((EMAIL_COL - name_end))
    [ "$padding_to_email" -lt 1 ] && padding_to_email=1
    
    printf "%s%*s%s%*s%s\n" "$prefix" "$padding_to_name" "" "$name" "$padding_to_email" "" "$email"
}

# Format SPDX line
format_spdx_line() {
    local spdx_part="$COMMENT_PREFIX SPDX-License-Identifier: $SPDX_LICENSE"
    local spdx_len=${#spdx_part}
    
    local padding_to_url=$((LICENSE_URL_COL - spdx_len))
    [ "$padding_to_url" -lt 1 ] && padding_to_url=1
    
    local url_end=$((LICENSE_URL_COL + ${#LICENSE_URL}))
    local padding_to_maintainer=$((MAINTAINER_COL - url_end))
    [ "$padding_to_maintainer" -lt 1 ] && padding_to_maintainer=1
    
    printf "%s%*s%s%*s%s\n" "$spdx_part" "$padding_to_url" "" "$LICENSE_URL" "$padding_to_maintainer" "" "$MAINTAINER_EMAIL"
}

# Check if file has a copyright header
has_copyright_header() {
    local file="$1"
    head -1 "$file" 2>/dev/null | grep -q "^$COMMENT_PREFIX[-=*]" && \
    head -2 "$file" 2>/dev/null | tail -1 | grep -q "Copyright (c)"
}

# Check if user email is in header
user_in_header() {
    local file="$1"
    local email="$2"
    head -10 "$file" 2>/dev/null | grep -q "$email"
}

# Get first copyright year from header
get_first_year() {
    local file="$1"
    head -2 "$file" | tail -1 | sed -n 's/.*Copyright (c) \([0-9]\{4\}\).*/\1/p'
}

# Create new copyright header
create_copyright_header() {
    local file="$1"
    local name="$2"
    local email="$3"
    local year="$4"
    
    local tmp_file
    tmp_file=$(mktemp)
    
    {
        generate_separator
        format_copyright_line "$year" "$name" "$email"
        format_spdx_line
        generate_separator
        echo
        cat "$file"
    } > "$tmp_file"
    
    mv "$tmp_file" "$file"
}

# Add contributor to existing header
add_contributor_to_header() {
    local file="$1"
    local name="$2"
    local email="$3"
    
    local new_line
    new_line=$(format_copyright_line "" "$name" "$email")
    
    local spdx_line_num
    spdx_line_num=$(grep -n "SPDX-License-Identifier" "$file" | head -1 | cut -d: -f1)
    
    if [ -n "$spdx_line_num" ]; then
        sed -i.bak "${spdx_line_num}i\\
${new_line}
" "$file"
        rm -f "${file}.bak"
    fi
}

# Update year range in header
update_year_in_header() {
    local file="$1"
    local first_year="$2"
    local current_year="$3"
    
    if [ "$first_year" = "$current_year" ]; then
        return 0
    fi
    
    if head -2 "$file" | tail -1 | grep -q "${first_year}-${current_year}"; then
        return 0
    fi
    
    # Simple replacement
    sed -i.bak "2s/Copyright (c) ${first_year}[^ ]*/Copyright (c) ${first_year}-${current_year}/" "$file"
    rm -f "${file}.bak"
    return 1
}
