//----------------------------------------------------------------------------------------------------
// Copyright (c) 2025-2026                    orgrinrt                    orgrinrt@ikiuni.dev
//                                      orgrinrt                 ort@hiisi.digital
// SPDX-License-Identifier: MPL-2.0      https://mozilla.org/MPL/2.0 contact@hiisi.digital
//----------------------------------------------------------------------------------------------------

/**
 * The hooks, generated as shell scripts and installed into `.githooks/`.
 *
 * They are written out rather than shipped so they carry the configuration they
 * were generated against, and installed by pointing `core.hooksPath` at the
 * directory rather than by writing into `.git/hooks`, which keeps them in the
 * repository and reviewable.
 *
 * @module
 */

import { run } from "../core/run.ts";
import { VERSION } from "../core/version.ts";

/**
 * Default hooks directory name.
 */
const HOOKS_DIR = ".githooks";

/**
 * Generates the content for the pre-commit hook script.
 */
export function generatePreCommitHook(version: string = VERSION): string {
  return `#!/bin/sh
#----------------------------------------------------------------------------------------------------
# ante - Copyright header management - Pre-commit hook
# Auto-generated by ante. Do not edit manually.
#----------------------------------------------------------------------------------------------------
#
# This hook runs 'ante fix' over the staged files and stages whatever it
# changed. It does not decide anything itself.
#
# It used to carry its own copy of the header engine, written in shell, and that
# copy did not know about anything the library learned: it put headers below a
# rust inner attribute, matched only files ending in .ts whatever the config
# said, and had no idea the contributor limit existed. Two implementations of one
# job disagree, and the one nobody tests is the one that runs on every commit.

set -e

# Whichever way ante is reachable here. A globally installed one first, since
# that is what somebody who installed it expects to run, then the two registries.
# The version is pinned to the one that wrote this hook, so a hook keeps behaving
# the way it did the day it was installed.
if command -v ante >/dev/null 2>&1; then
    ANTE="ante"
elif command -v deno >/dev/null 2>&1; then
    ANTE="deno run --allow-read --allow-write --allow-run --allow-env jsr:@hiisi/ante@${version}/cli"
elif command -v npx >/dev/null 2>&1; then
    ANTE="npx --yes ante-cli@${version}"
else
    echo "ante: not reachable, and neither deno nor npx is on the path."
    echo "ante: headers are not being checked on this commit."
    exit 0
fi

STAGED=$(git diff --cached --name-only --diff-filter=ACM)
[ -z "$STAGED" ] && exit 0

# Which of them ante actually claims is ante's business, not this script's: the
# include and exclude globs live in the config and a hook second-guessing them is
# how the two get to disagree.
# shellcheck disable=SC2086
$ANTE fix $STAGED || exit 1

CHANGED=$(git diff --name-only -- $STAGED)
if [ -n "$CHANGED" ]; then
    # shellcheck disable=SC2086
    git add $CHANGED
    echo ""
    echo "Copyright headers have been updated. Changes have been staged."
fi

exit 0
`;
}

/**
 * Generates the content for the commit-msg hook (conventional commits).
 */
export function generateCommitMsgHook(): string {
  return `#!/bin/sh
#----------------------------------------------------------------------------------------------------
# Conventional commits enforcement hook
# Auto-generated by ante.
#----------------------------------------------------------------------------------------------------

commit_msg_file=$1
commit_msg=$(head -1 "$commit_msg_file")

# A merge or a fixup is git's wording, not the author's, and holding it to this
# blocks an ordinary merge for a reason nobody can act on.
case "$commit_msg" in
  "Merge "*|"Revert "*|"fixup!"*|"squash!"*|"#"*) exit 0 ;;
esac

# The spec's shape: a type, an optional scope in parentheses, an optional '!' for
# a breaking change, then the subject. The '!' was missing here, so every
# breaking change any project using this hook wanted to mark was refused, and the
# only way past it was to drop the mark.
#
# 72 is git's own subject convention. It used to be 50, which is the soft advice
# for the summary line and reads as a format error when a longer subject is
# refused for a reason the message does not mention.
types="feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert"
pattern="^($types)(\\([a-z0-9_.-]+\\))?!?: .{1,72}$"

if ! echo "$commit_msg" | grep -qE "$pattern"; then
  echo "Commit message does not follow Conventional Commits."
  echo "  <type>[(scope)][!]: <subject>, subject at most 72 characters"
  echo "  types: $types"
  echo "  for example: feat: add new feature, or refactor!: rename the export"
  echo "  yours: $commit_msg"
  exit 1
fi
`;
}

/**
 * Installs the git hooks to the specified directory.
 *
 * It takes no configuration. The hook it writes runs `ante fix`, which reads the
 * config itself at the moment it runs, so a hook installed today keeps working
 * after the config changes. Baking the settings into the hook is what the shell
 * copy did, and it is how the two came to disagree.
 *
 * @param targetDir - The project root directory
 * @returns Promise resolving when installation is complete
 */
export async function installHook(
  targetDir: string,
): Promise<void> {
  const hooksDir = `${targetDir}/${HOOKS_DIR}`;

  // Create hooks directory
  await Deno.mkdir(hooksDir, { recursive: true });

  // Write pre-commit hook
  const preCommitPath = `${hooksDir}/pre-commit`;
  await Deno.writeTextFile(preCommitPath, generatePreCommitHook());
  await Deno.chmod(preCommitPath, 0o755);

  // Write commit-msg hook
  const commitMsgPath = `${hooksDir}/commit-msg`;
  await Deno.writeTextFile(commitMsgPath, generateCommitMsgHook());
  await Deno.chmod(commitMsgPath, 0o755);

  // Configure git to use the hooks directory.
  //
  // `-C targetDir`, because the hooks were written into `targetDir` and this
  // used to run wherever the process happened to be standing. Installing into
  // any directory but the current one wrote the hooks to one repository and
  // pointed a different one at them.
  //
  // The result is not read: git either sets the path or it does not, and there is
  // nothing useful to do about the second case here.
  await run("git", ["-C", targetDir, "config", "core.hooksPath", HOOKS_DIR]);
}

/**
 * Removes the installed hooks and resets git configuration.
 *
 * @param targetDir - The project root directory
 * @returns Promise resolving when uninstallation is complete
 */
export async function uninstallHook(targetDir: string): Promise<void> {
  const hooksDir = `${targetDir}/${HOOKS_DIR}`;

  // Remove hooks directory
  try {
    await Deno.remove(hooksDir, { recursive: true });
  } catch {
    // Directory might not exist
  }

  // Reset git hooks path
  // Unsetting something that is not set is not an error worth reporting.
  await run("git", ["-C", targetDir, "config", "--unset", "core.hooksPath"]);
}

/**
 * Checks if hooks are installed.
 *
 * @param targetDir - The project root directory
 * @returns Promise resolving to true if hooks are installed
 */
export async function hooksInstalled(targetDir: string): Promise<boolean> {
  const hooksDir = `${targetDir}/${HOOKS_DIR}`;

  try {
    const stat = await Deno.stat(`${hooksDir}/pre-commit`);
    return stat.isFile;
  } catch {
    return false;
  }
}
