//----------------------------------------------------------------------------------------------------
// Copyright (c) 2025-2026                    orgrinrt                    orgrinrt@ikiuni.dev
//                                      orgrinrt                 ort@hiisi.digital
// SPDX-License-Identifier: MPL-2.0      https://mozilla.org/MPL/2.0 contact@hiisi.digital
//----------------------------------------------------------------------------------------------------

/**
 * The hooks, generated as shell scripts and installed into `.githooks/`.
 *
 * They are written out rather than shipped so they carry the configuration they
 * were generated against, and installed by pointing `core.hooksPath` at the
 * directory rather than by writing into `.git/hooks`, which keeps them in the
 * repository and reviewable.
 *
 * @module
 */

import { relative, resolve } from "@std/path";
import { run } from "../core/run.ts";
import { VERSION } from "../core/version.ts";

/**
 * Default hooks directory name.
 */
const HOOKS_DIR = ".githooks";

/**
 * Generates the content for the pre-commit hook script.
 */
export function generatePreCommitHook(version: string = VERSION): string {
  return `#!/bin/sh
#----------------------------------------------------------------------------------------------------
# ante - Copyright header management - Pre-commit hook
# Auto-generated by ante. Do not edit manually.
#----------------------------------------------------------------------------------------------------
#
# Runs 'ante fix' over the staged files and stages whatever it changed. Which
# files are ante's business is decided by the include and exclude patterns in the
# project's config, not here.
#
# Needs ante, deno or npx on the path. With none of them it says so and lets the
# commit through.

set -e

STAGED_LIST=$(mktemp)
CHANGED_LIST=$(mktemp)
trap 'rm -f "$STAGED_LIST" "$CHANGED_LIST"' EXIT

# Whichever way ante is reachable here. A globally installed one first, since
# that is what somebody who installed it expects to run, then the two registries.
# The version is pinned to the one that wrote this hook, so a hook keeps behaving
# the way it did the day it was installed.
if command -v ante >/dev/null 2>&1; then
    ANTE="ante"
elif command -v deno >/dev/null 2>&1; then
    ANTE="deno run --allow-read --allow-write --allow-run=git --allow-env jsr:@hiisi/ante@${version}/cli"
elif command -v npx >/dev/null 2>&1; then
    ANTE="npx --yes ante-cli@${version}"
else
    echo "ante: not reachable, and neither deno nor npx is on the path."
    echo "ante: headers are not being checked on this commit."
    exit 0
fi

# -z, so a path with a space in it survives as one argument rather than two, and
# git hands back the raw bytes instead of a quoted escape for a non-ascii name.
git diff --cached --name-only --diff-filter=ACM -z > "$STAGED_LIST"
[ ! -s "$STAGED_LIST" ] && exit 0

# Every staged path in one call. Which of them ante actually claims is ante's
# business, not this script's: the include and exclude globs live in the config
# and a hook second-guessing them is how the two get to disagree.
xargs -0 $ANTE fix < "$STAGED_LIST" || exit 1

xargs -0 git diff --name-only -z -- < "$STAGED_LIST" > "$CHANGED_LIST"
if [ -s "$CHANGED_LIST" ]; then
    xargs -0 git add < "$CHANGED_LIST"
    echo ""
    echo "Copyright headers have been updated. Changes have been staged."
fi

exit 0
`;
}

/**
 * Generates the content for the commit-msg hook (conventional commits).
 */
export function generateCommitMsgHook(): string {
  return `#!/bin/sh
#----------------------------------------------------------------------------------------------------
# Conventional commits enforcement hook
# Auto-generated by ante.
#----------------------------------------------------------------------------------------------------

commit_msg_file=$1
commit_msg=$(head -1 "$commit_msg_file")

# A merge or a fixup is git's wording, not the author's, and holding it to this
# blocks an ordinary merge for a reason nobody can act on.
case "$commit_msg" in
  "Merge "*|"Revert "*|"fixup!"*|"squash!"*|"#"*) exit 0 ;;
esac

# A type, an optional scope in parentheses, an optional '!' marking a breaking
# change, then the subject, which may run to 72 characters.
types="feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert"
pattern="^($types)(\\([A-Za-z0-9_.\\/-]+\\))?!?: .{1,72}$"

if ! echo "$commit_msg" | grep -qE "$pattern"; then
  echo "Commit message does not follow Conventional Commits."
  echo "  <type>[(scope)][!]: <subject>, subject at most 72 characters"
  echo "  types: $types"
  echo "  for example: feat: add new feature, or refactor!: rename the export"
  echo "  yours: $commit_msg"
  exit 1
fi
`;
}

/**
 * Installs the git hooks to the specified directory.
 *
 * It takes no configuration. The hook it writes runs `ante fix`, which reads the
 * config itself at the moment it runs, so a hook installed today keeps working
 * after the config changes. Baking the settings into the hook is what the shell
 * copy did, and it is how the two came to disagree.
 *
 * @param targetDir - The project root directory
 * @returns Promise resolving when installation is complete
 */
export async function installHook(
  targetDir: string,
): Promise<void> {
  const hooksDir = `${targetDir}/${HOOKS_DIR}`;

  // Create hooks directory
  await Deno.mkdir(hooksDir, { recursive: true });

  // Write pre-commit hook
  const preCommitPath = `${hooksDir}/pre-commit`;
  await Deno.writeTextFile(preCommitPath, generatePreCommitHook());
  await Deno.chmod(preCommitPath, 0o755);

  // Write commit-msg hook
  const commitMsgPath = `${hooksDir}/commit-msg`;
  await Deno.writeTextFile(commitMsgPath, generateCommitMsgHook());
  await Deno.chmod(commitMsgPath, 0o755);

  // Point git at them, on the repository the hooks were written into and with a
  // path that repository can resolve.
  //
  // `core.hooksPath` is resolved from the worktree root rather than from the
  // directory it was configured in, so a bare `.githooks` names the wrong place
  // whenever `targetDir` is a subdirectory of the repository. `init --dir` on a
  // package folder is exactly that, and the result is a hook git never runs and
  // never mentions.
  //
  // The result is not read: git either sets the path or it does not, and there
  // is nothing useful to do about the second case here.
  await run("git", ["-C", targetDir, "config", "core.hooksPath", await hooksPathFor(targetDir)]);
}

/**
 * What to write into `core.hooksPath` so the repository containing `targetDir`
 * resolves it to the hooks that were just written there.
 *
 * Relative to the worktree root where that can be worked out, since the value is
 * read by a person as often as by git. Absolute where it cannot, which is better
 * than a relative path resolved against somewhere else.
 */
async function hooksPathFor(targetDir: string): Promise<string> {
  const absolute = resolve(targetDir, HOOKS_DIR);
  const top = await run("git", ["-C", targetDir, "rev-parse", "--show-toplevel"]);
  const root = top.stdout.trim();
  if (root === "") return absolute;
  const from = relative(root, absolute);
  // A path climbing out of the root is not a path that root can resolve.
  return from === "" || from.startsWith("..") ? absolute : from;
}

/**
 * Removes the installed hooks and resets git configuration.
 *
 * @param targetDir - The project root directory
 * @returns Promise resolving when uninstallation is complete
 */
export async function uninstallHook(targetDir: string): Promise<void> {
  const hooksDir = `${targetDir}/${HOOKS_DIR}`;

  // Remove hooks directory
  try {
    await Deno.remove(hooksDir, { recursive: true });
  } catch {
    // Directory might not exist
  }

  // Reset git hooks path
  // Unsetting something that is not set is not an error worth reporting.
  await run("git", ["-C", targetDir, "config", "--unset", "core.hooksPath"]);
}

/**
 * Checks if hooks are installed.
 *
 * @param targetDir - The project root directory
 * @returns Promise resolving to true if hooks are installed
 */
export async function hooksInstalled(targetDir: string): Promise<boolean> {
  const hooksDir = `${targetDir}/${HOOKS_DIR}`;

  try {
    const stat = await Deno.stat(`${hooksDir}/pre-commit`);
    return stat.isFile;
  } catch {
    return false;
  }
}
